### PR TITLE
Fix error type

### LINKED ISSUE #15: `ErrNoSuchField` is undefined
This does not build.

```
./adifrecord.go:118:16: undefined: ErrNoSuchField
```

_Originally posted by @xylo04 in https://github.com/Matir/adifparser/issues/14#issuecomment-1295118845_

### PR DESCRIPTION
**Pull request by xylo04**
Fixes #15

### CODE REVIEW

**Comment by xylo04** [comment]
@Matir any concerns?

**Comment by xylo04** [comment]
@Matir this is a trivial PR to repair a compile-time breakage. I hope you can review this soon.

**Comment by Matir** [comment]
Sorry about the delay, not very responsible of me :(

**Comment by xylo04** [comment]
Thank you! 😃

**Pull request merged**
